version: "3.7"
services:
  grpc-server:
    build:
      context: ./grpc-server
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    networks:
      - app

  springboot-server:
    build:
      context: ./spring-boot-server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app

  benchmark-client:
    build:
      context: ./benchmark-client
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - app
    environment:
      - grpcServer=grpc-server:50051
      - springBootServer=http://springboot-server:8081

networks:
  app: {}
